import { useState, useMemo, type CSSProperties, type SyntheticEvent } from "react";

export interface SmartImageProps {
  /** Path to the original jpg/png in /public, e.g. "/games/dice.jpg" */
  src: string;
  alt: string;
  width?: number;
  height?: number;
  /** CSS `sizes` attribute — required for correct responsive selection */
  sizes?: string;
  className?: string;
  style?: CSSProperties;
  loading?: "lazy" | "eager";
  decoding?: "async" | "sync" | "auto";
  fetchPriority?: "high" | "low" | "auto";
  draggable?: boolean;
}

const WIDTHS = [480, 960] as const;

// Only these directories are processed by scripts/gen-image-variants.mjs —
// avoid emitting a <source srcset> for images we know have no variants
// (that would produce a broken image, since <picture> won't fall back to
// the <img> once a <source> is selected).
const VARIANT_DIRS = ["/games/", "/games/new/", "/bg/", "/symbols/"];

function variantBase(src: string) {
  const m = src.match(/^(.*)\.(jpe?g|png)$/i);
  if (!m) return null;
  if (!VARIANT_DIRS.some((d) => src.startsWith(d))) return null;
  return m[1];
}

/**
 * Renders a responsive, sharp <img> using <picture> with webp srcset variants
 * (generated by scripts/gen-image-variants.mjs) and a jpg/png fallback.
 * Never renders broken — falls back to the original file via onError.
 */
export default function SmartImage({
  src,
  alt,
  width,
  height,
  sizes = "33vw",
  className,
  style,
  loading = "lazy",
  decoding = "async",
  fetchPriority = "auto",
  draggable,
}: SmartImageProps) {
  const [broken, setBroken] = useState(false);
  const base = useMemo(() => variantBase(src), [src]);

  const webpSrcSet = base
    ? WIDTHS.map((w) => `${base}-${w}.webp ${w}w`).join(", ")
    : undefined;

  const handleError = (e: SyntheticEvent<HTMLImageElement>) => {
    // Guard against infinite loop if even the original is missing.
    if (e.currentTarget.src.endsWith(src)) return;
    setBroken(true);
  };

  if (broken || !webpSrcSet) {
    return (
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        className={className}
        style={{ objectFit: "cover", ...style }}
        loading={loading}
        decoding={decoding}
        // @ts-expect-error fetchPriority is valid but not yet in some TS DOM libs
        fetchpriority={fetchPriority}
        draggable={draggable}
      />
    );
  }

  return (
    <picture>
      <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        sizes={sizes}
        className={className}
        style={{ objectFit: "cover", ...style }}
        loading={loading}
        decoding={decoding}
        // @ts-expect-error fetchPriority is valid but not yet in some TS DOM libs
        fetchpriority={fetchPriority}
        draggable={draggable}
        onError={handleError}
      />
    </picture>
  );
}
